name: terra-test
favicon: null
layout_spectrum: 0.98332
typography_spectrum: 0.32864
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.8125
  lightness: 0.1875
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
